"""
RAVANA Sub-Answer Synthesizer
==============================
Combines sub-answers from the QuestionDecompositionEngine into coherent,
multi-perspective responses. Integrates with the existing SurfaceRealizer,
syntactic assembly, and discourse planning infrastructure.

Inspired by:
- DMN (Default Mode Network) integration: the brain's default mode network
  integrates disparate pieces of information into a coherent narrative
  (Buckner et al., 2008; Spreng & Grady, 2010)
- Mental model integration (Johnson-Laird, 1983): combining multiple mental
  models into a unified understanding
- Working memory chunking: compressing sub-answers into higher-level chunks
  to reduce cognitive load (Gobet et al., 2001)
"""

from __future__ import annotations
import re
import random
from typing import List, Optional, Dict, Any, Tuple
from .question_decomposition import (
    DecompositionResult, 
    SubQuestion, 
    QuestionCategory,
)


class SubAnswerSynthesizer:
    """Synthesizes sub-answers into a coherent narrative response.
    
    Each sub-answer is a complete response generated by Ravana's pipeline 
    (graph walk + surface realizer). The synthesizer weaves them together
    using discourse transitions, pronominal references, and logical flow.
    
    Instead of appending sentences with generic transitions, it uses the
    synthesis plan from the decomposition engine to build a structured
    answer that addresses the original question from multiple angles.
    """
    
    # Discourse transitions for connecting sub-answers
    _TRANSITIONS = {
        "category": [
            "at its core",
            "fundamentally",
            "in essence",
            "essentially",
        ],
        "properties": [
            "one key aspect is",
            "a defining feature is",
            "what makes it distinctive is",
            "it is characterized by",
        ],
        "process": [
            "in practical terms",
            "mechanistically",
            "how it works is",
            "the way it operates is",
        ],
        "cause": [
            "this happens because",
            "the reason is",
            "it stems from",
            "at the root of this is",
        ],
        "mechanism": [
            "the mechanism involves",
            "this occurs through",
            "the process works like this",
            "step by step",
        ],
        "conditions": [
            "this typically happens when",
            "it occurs under specific conditions",
            "certain factors influence this",
            "context matters here",
        ],
        "significance": [
            "why this matters is",
            "the significance of this is",
            "this is important because",
            "what this means for us is",
        ],
        "components": [
            "it consists of several parts",
            "the key components are",
            "at its most basic level",
            "breaking it down",
        ],
        "functions": [
            "each part plays a role",
            "the function of each is",
            "they each contribute by",
            "their roles are",
        ],
        "interaction": [
            "they work together by",
            "the interaction between them",
            "they combine to create",
            "together they form",
        ],
        "definition": [
            "broadly speaking",
            "commonly understood as",
            "the standard definition is",
            "in general terms",
        ],
        "perspectives": [
            "there are different ways to see this",
            "perspectives vary",
            "interestingly",
            "from another angle",
        ],
        "connection": [
            "this relates to",
            "it connects with",
            "this is linked to",
            "in human experience",
        ],
        "baseline": [
            "to understand this, first consider",
            "normally",
            "under ordinary circumstances",
            "in the usual course of things",
        ],
        "immediate": [
            "the immediate effect would be",
            "right away",
            "instantly",
            "the first thing that would happen is",
        ],
        "cascade": [
            "then, cascading from that",
            "this would then lead to",
            "consequently",
            "as a ripple effect",
        ],
        "longterm": [
            "over time",
            "in the long run",
            "eventually",
            "the ultimate outcome would be",
        ],
        "paradox": [
            "this is a paradox because",
            "the puzzle here is",
            "what makes this fascinating is",
            "at first glance this seems contradictory",
        ],
        "interest": [
            "humans find this intriguing because",
            "this captures our imagination because",
            "what draws us to this question is",
            "this matters to us because",
        ],
        "insight": [
            "what this reveals about thinking is",
            "this teaches us that",
            "the deeper insight is",
            "perhaps the real lesson is",
        ],
        "differences": [
            "the key difference is",
            "where they diverge is",
            "what sets them apart is",
            "they differ in that",
        ],
        "similarities": [
            "despite their differences",
            "what they share is",
            "they are alike in that",
            "in common they have",
        ],
        "example": [
            "for example",
            "as an illustration",
            "consider",
            "one concrete example is",
        ],
        "response": [""],  # No transition for single responses
    }
    
    # Fallback transitions when specific plan item has no match
    _FALLBACK_TRANSITIONS = [
        "also",
        "furthermore",
        "in addition",
        "moreover",
        "beyond that",
    ]

    def __init__(self):
        self._last_subject: str = ""
        self._last_synthesis: str = ""

    def synthesize(self, 
                   result: DecompositionResult,
                   answered: List[SubQuestion],
                   vector_fn=None,
                   surface_realizer=None,
                   syntactic_assembly=None,
                   discourse_state=None) -> Optional[str]:
        """Synthesize answered sub-questions into a coherent response.
        
        Uses the synthesis plan from the decomposition result to build
        a structured, multi-perspective answer.
        
        Args:
            result: The decomposition result with synthesis plan
            answered: List of answered sub-questions (sorted by id)
            vector_fn: Optional GloVe vector function for semantic coherence
            surface_realizer: Optional SurfaceRealizer for fluent generation
            syntactic_assembly: Optional SyntacticCellAssembly for frame binding
            discourse_state: Optional discourse context
            
        Returns:
            Synthesized response text, or None if synthesis fails
        """
        if not answered:
            return None
        
        synthesis_plan = result.synthesis_plan
        subject = result.main_subject
        category = result.category
        
        # Build the synthesized response
        utterances = self._build_utterances(
            answered, synthesis_plan, subject, category,
            vector_fn, surface_realizer, syntactic_assembly, discourse_state
        )
        
        if not utterances:
            return None
        
        # Combine into a coherent narrative
        response = self._weave_narrative(utterances, subject, category)
        
        self._last_subject = subject
        self._last_synthesis = response
        
        return response

    def _build_utterances(self,
                          answered: List[SubQuestion],
                          synthesis_plan: List[str],
                          subject: str,
                          category: QuestionCategory,
                          vector_fn=None,
                          surface_realizer=None,
                          syntactic_assembly=None,
                          discourse_state=None) -> List[Dict[str, str]]:
        """Build structured utterances with transitions from sub-answers.

        Each utterance has a 'text' and 'transition_type' for weaving.
        Near-duplicate sub-answers (the web search repeatedly surfacing the
        same dominant snippet for every sub-question) are collapsed so a
        decomposition does not parrot one sentence 3-4 times.
        """
        seen_norm: List[str] = []
        utterances = []

        for i, plan_item in enumerate(synthesis_plan):
            if i >= len(answered):
                break

            sq = answered[i]
            answer_text = sq.answer

            if not answer_text or len(answer_text) < 5:
                continue

            # Deduplicate: drop a sub-answer that is a near-copy of one already
            # woven (长短/whitespace-insensitive; keep the first occurrence).
            _norm = re.sub(r"\s+", " ", answer_text.strip().lower())
            _norm_core = _norm[:120]  # leading 120 chars catch sentence-level repeats
            if any(_norm_core == s[:120] for s in seen_norm):
                continue
            seen_norm.append(_norm)

            # Pick the appropriate transition for this plan item
            transition = self._pick_transition(plan_item, i == 0)
            
            utterances.append({
                "text": answer_text,
                "transition": transition,
                "transition_type": plan_item,
                "is_first": i == 0,
                "is_last": i == len(synthesis_plan) - 1,
            })
        
        return utterances

    def _pick_transition(self, plan_item: str, is_first: bool) -> str:
        """Pick an appropriate discourse transition for a plan item.
        
        The first utterance gets no transition (or a very soft one).
        Subsequent utterances get transitions that match their plan role.
        """
        if is_first:
            return ""
        
        transitions = self._TRANSITIONS.get(plan_item)
        if transitions:
            return random.choice(transitions)
        
        # Fallback to generic transitions
        return random.choice(self._FALLBACK_TRANSITIONS)

    def _weave_narrative(self, 
                         utterances: List[Dict[str, str]], 
                         subject: str,
                         category: QuestionCategory) -> str:
        """Weave utterances into a coherent narrative with discourse flow.
        
        The weaving process:
        1. First utterance is presented directly (or with minimal lead-in)
        2. Subsequent utterances are connected with appropriate transitions
        3. The final utterance may include a question back to the user
        4. Pronominal references are used to avoid repetition
        
        Inspired by the DMN's narrative construction process:
        the brain doesn't list facts — it tells a story
        """
        if not utterances:
            return ""
        
        sentences = []
        
        for i, utt in enumerate(utterances):
            text = utt["text"].strip()
            if not text:
                continue
            
            # Clean the text: capitalize first letter, ensure ending punctuation
            text = text[0].upper() + text[1:] if text else text
            if not text.endswith((".", "?", "!")):
                text += "."
            
            # Add transition for non-first utterances
            if not utt["is_first"] and utt["transition"]:
                # Decide whether to use the transition as a lead-in or embedded
                if random.random() < 0.6:
                    # Transition as separate lead-in phrase
                    transition_text = utt["transition"][0].upper() + utt["transition"][1:]
                    text = f"{transition_text}, {text[0].lower()}{text[1:]}"
                else:
                    # Transition embedded at start
                    text = f"{utt['transition']} {text[0].lower()}{text[1:]}"
            
            sentences.append(text)
        
        if not sentences:
            return ""
        
        # Join sentences with spaces
        combined = " ".join(sentences)
        
        # Replace subject repetition with pronouns when appropriate
        combined = self._pronominalize(combined, subject)
        
        # Clean up whitespace
        combined = re.sub(r'\s+', ' ', combined)
        
        return combined

    def _pronominalize(self, text: str, subject: str) -> str:
        """Replace repeated subject mentions with pronouns for natural flow.
        
        Human speakers don't repeat the subject in every sentence.
        The brain's DMN naturally uses pronominal reference to maintain
        topic continuity (Givón, 1983).
        """
        if not subject or len(subject) < 2:
            return text
        
        subj_lower = subject.lower().strip()
        
        # Only pronominalize if subject appears more than once
        occurrences = len(re.findall(r'\b' + re.escape(subj_lower) + r'\b', text.lower()))
        if occurrences <= 1:
            return text
        
        # Replace second and subsequent occurrences with pronouns
        # Determine pronoun based on subject characteristics
        pronoun = "it"
        if subj_lower in ("people", "humans", "they", "we"):
            pronoun = "they"
        elif subj_lower in ("you", "i", "he", "she"):
            pronoun = subj_lower
        
        # Only replace when it's clearly the subject of a sentence.
        # Split on any sentence terminator (.!?) followed by whitespace, so
        # "!" / "?" joins and newline joins are handled too (not just ". ").
        parts = re.split(r'(?<=[.!?])\s+', text)
        if len(parts) <= 1:
            return text
        
        new_parts = [parts[0]]  # Keep first sentence as-is
        for part in parts[1:]:
            # Check if part starts with the subject (capitalized or lowercase).
            pattern = r'^' + re.escape(subj_lower[0].upper() + subj_lower[1:]) + r'\b'
            if re.match(pattern, part):
                part = re.sub(pattern, pronoun[0].upper() + pronoun[1:], part, count=1)
            else:
                pattern = r'^' + re.escape(subj_lower) + r'\b'
                if re.match(pattern, part.lower()):
                    part = re.sub(pattern, pronoun, part, count=1)
            new_parts.append(part)
        
        return " ".join(new_parts)

    def get_synthesis_status(self) -> Dict[str, Any]:
        """Return status of the last synthesis operation."""
        return {
            "last_subject": self._last_subject,
            "has_synthesis": bool(self._last_synthesis),
            "synthesis_length": len(self._last_synthesis) if self._last_synthesis else 0,
        }


# ─── Integration Helper ───

def build_decomposed_response(
    decomposition_result: DecompositionResult,
    sub_answers: List[Tuple[SubQuestion, str, float]],
    vector_fn=None,
    surface_realizer=None,
    syntactic_assembly=None,
) -> Optional[str]:
    """Convenience function: build a response from a decomposition and its answers.
    
    Args:
        decomposition_result: The decomposition from QuestionDecompositionEngine
        sub_answers: List of (SubQuestion, answer_text, confidence) tuples
        vector_fn: Optional GloVe vector function
        surface_realizer: Optional SurfaceRealizer
        syntactic_assembly: Optional SyntacticCellAssembly
    
    Returns:
        Synthesized response text, or None
    """
    synthesizer = SubAnswerSynthesizer()
    
    # Populate sub-questions with answers
    for sq, answer, confidence in sub_answers:
        sq.answer = answer
        sq.confidence = confidence
        sq.is_answered = True
    
    answered = sorted(
        [sq for sq, _, _ in sub_answers],
        key=lambda sq: sq.id
    )
    
    return synthesizer.synthesize(
        result=decomposition_result,
        answered=answered,
        vector_fn=vector_fn,
        surface_realizer=surface_realizer,
        syntactic_assembly=syntactic_assembly,
    )
