#!/usr/bin/env python3
"""Generate or update docs/API_REFERENCE.md by scanning source trees.

Usage:
    python scripts/gen_api_ref.py              # write to stdout
    python scripts/gen_api_ref.py --write       # update docs/API_REFERENCE.md in place
    python scripts/gen_api_ref.py --check       # exit 1 if file is stale

Scans all .py files under ravana/src/, ravana_ml/src/, and ravana-v2/src/
for class and function definitions, then outputs a Markdown reference table
organized by package and module.
"""
import ast
import os
import sys
from pathlib import Path
from typing import List, Tuple, Optional

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "API_REFERENCE.md"

PACKAGES = {
    "ravana_ml — ML Substrate": ROOT / "ravana_ml" / "src" / "ravana_ml",
    "ravana — Chat Engine": ROOT / "ravana" / "src" / "ravana",
    "ravana_grace — GRACE Cognitive Core": ROOT / "ravana-v2" / "src" / "ravana_grace",
}


def scan_file(path: Path) -> List[Tuple[str, str, int]]:
    """Return list of (name, kind, line_no) for top-level classes and functions."""
    results: List[Tuple[str, str, int]] = []
    try:
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(path))
    except (SyntaxError, UnicodeDecodeError):
        return results

    # Only top-level definitions (direct children of the module)
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            results.append((node.name, "class", node.lineno or 0))
        elif isinstance(node, ast.FunctionDef):
            results.append((node.name, "def", node.lineno or 0))
        elif isinstance(node, ast.AsyncFunctionDef):
            results.append((node.name, "async def", node.lineno or 0))
    return results


def scan_package(name: str, path: Path) -> str:
    """Scan a package directory and return its Markdown section."""
    lines: List[str] = []
    lines.append(f"## `{name}`\n")
    lines.append(f"Path: `{os.path.relpath(path, str(ROOT))}/`\n")

    if not path.exists():
        lines.append("_(directory not found)_\n")
        return "\n".join(lines)

    # Collect all .py files
    py_files = sorted(path.rglob("*.py"))
    
    # Group by submodule
    sections: List[Tuple[str, List[Tuple[str, str, int]]]] = []
    for f in py_files:
        if f.name == "__init__.py":
            continue
        rel = f.relative_to(path)
        module = str(rel.with_suffix("")).replace(os.sep, ".")
        entries = scan_file(f)
        if entries:
            sections.append((f"{module}.py", entries))

    if not sections:
        lines.append("_(no classes or functions found)_\n")
        return "\n".join(lines)

    for module_name, entries in sections:
        lines.append(f"| `{module_name}.py` | `{entries[0][0]}` | {entries[0][1]} (line {entries[0][2]}) |")
        for name, kind, line_no in entries[1:]:
            lines.append(f"| | `{name}` | {kind} (line {line_no}) |")
        lines.append("")

    return "\n".join(lines)


def generate_auto_section() -> str:
    """Generate the machine-readable function/class index."""
    lines: List[str] = []
    lines.append("\n---\n")
    lines.append("## Auto-Generated Index\n")
    lines.append("> This section is auto-generated by `scripts/gen_api_ref.py`.\n")
    lines.append("> Regenerate with: `python scripts/gen_api_ref.py --write`\n")

    for name, path in PACKAGES.items():
        section = scan_package(name, path)
        if "_(no classes" not in section and "_(directory not found" not in section:
            lines.append(section)

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    gen_section = generate_auto_section()
    gen_marker = "\n---\n## Auto-Generated Index"

    if "--write" in sys.argv:
        if OUTPUT.exists():
            existing = OUTPUT.read_text(encoding="utf-8")
            # Preserve the hand-written portion, replace auto-generated section
            if gen_marker in existing:
                before = existing.split(gen_marker)[0]
                content = before + gen_section
            else:
                content = existing + gen_section
        else:
            content = "# API Reference\n\nHand-written descriptions go above this line.\n" + gen_section
        OUTPUT.write_text(content, encoding="utf-8")
        print(f"[OK] Updated {OUTPUT}")
    elif "--check" in sys.argv:
        if not OUTPUT.exists():
            print(f"[MISSING] {OUTPUT} does not exist. Run `--write` to create it.")
            sys.exit(1)
        existing = OUTPUT.read_text(encoding="utf-8")
        existing_gen = existing.split(gen_marker)[-1] if gen_marker in existing else ""
        new_gen = gen_section
        if existing_gen != new_gen:
            print(f"[STALE] {OUTPUT} auto-generated section is out of date.")
            sys.exit(1)
        print(f"[OK] {OUTPUT} is up to date.")
    else:
        print(gen_section)
